// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only (generate/migrate/studio) — usa a conexão direta pra evitar
    // que `migrate deploy` tente tirar advisory lock via pooler (PgBouncer
    // em modo transaction não sustenta lock de sessão -> timeout P1002).
    // Runtime da app (src/lib/prisma.ts) continua na pooled via DATABASE_URL.
    url: process.env.DATABASE_URL_UNPOOLED ?? process.env.DATABASE_URL,
  },
});
